---
output: rmarkdown::github_document
---


```{r}
library(ggplot2)
```


```{r}
data = read.csv('datasets/Raisin_Dataset.csv', header=TRUE, sep=";")
```

```{r}
summary(data)
```

Correlogram (Aim: Find possible correlation among variables)

```{r}
plot(data)
```


Boxplots (Aim: Identify outliers)


```{r}
boxplot(data$Area)
```


```{r}
boxplot(data$MajorAxisLength)
```


```{r}
boxplot(data$MinorAxisLength)
```

```{r}
boxplot(data$Eccentricity)
```


```{r}
boxplot(data$ConvexArea)
```


```{r}
boxplot(data$Extent)
```


```{r}
boxplot(data$Perimeter)
```



```{r}
boxplot(data$Class)
```


Histograms highlighting class differences (Aim: See if variables' distribution depend on Class)


```{r}
ggplot() + geom_histogram(data = subset(x=data, subset=Class==1), aes(x = Area), fill = 'black', alpha = 0.5) + geom_histogram(data = subset(x=data, subset=Class==0), aes(x = Area), fill='yellow', alpha = 0.5) 
```

```{r}
ggplot() + geom_histogram(data = subset(x=data, subset=Class==1), aes(x = MajorAxisLength), fill = 'black', alpha = 0.5) + geom_histogram(data = subset(x=data, subset=Class==0), aes(x = MajorAxisLength), fill='yellow', alpha = 0.5)
```


```{r}
ggplot() + geom_histogram(data = subset(x=data, subset=Class==1), aes(x = MinorAxisLength), fill = 'black', alpha = 0.5) + geom_histogram(data = subset(x=data, subset=Class==0), aes(x = MinorAxisLength), fill='yellow', alpha = 0.5)
```


```{r}
ggplot() + geom_histogram(data = subset(x=data, subset=Class==1), aes(x = Eccentricity), fill = 'black', alpha = 0.5) + geom_histogram(data = subset(x=data, subset=Class==0), aes(x = Eccentricity), fill='yellow', alpha = 0.5)
```


```{r}
ggplot() + geom_histogram(data = subset(x=data, subset=Class==1), aes(x = ConvexArea), fill = 'black', alpha = 0.5) + geom_histogram(data = subset(x=data, subset=Class==0), aes(x = ConvexArea), fill='yellow', alpha = 0.5)
```


```{r}
ggplot() + geom_histogram(data = subset(x=data, subset=Class==1), aes(x = Extent), fill = 'black', alpha = 0.5) + geom_histogram(data = subset(x=data, subset=Class==0), aes(x = Extent), fill='yellow', alpha = 0.5)
```

```{r}
ggplot() + geom_histogram(data = subset(x=data, subset=Class==1), aes(x = Perimeter), fill = 'black', alpha = 0.5) + geom_histogram(data = subset(x=data, subset=Class==0), aes(x = Perimeter), fill='yellow', alpha = 0.5)
```












