---
title: "models"
author: "Casual depp learning"
date: "2023-05-30"
output:
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(dplyr)
library(estimatr)
library(stats)
library(tree)
```
```{r}
# Load the dataset
raisins <- read.csv("https://raw.githubusercontent.com/LeonardoAcquaroli/raisins_and_mushrooms/main/datasets/Raisin_Dataset.csv", sep=";")
# Remove the column of the literal class
raisins <- raisins[-c(8)]
# Scale Area by 1000 for better interpretability
raisins$Area <- raisins$Area / 1000
```
```{r}
# 1. OLS
ols <- lm(Class ~ ., data = raisins)
summary(ols)
```
```{r}
# 2. Robust OLS
ols_robust <- lm_robust(Class ~ ., data = raisins, se_type = "HC1")
summary(ols_robust)
```
```{r}
# 3. Logistic regression
logistic <- glm(Class ~ ., data = raisins, family = binomial(link='logit'))
hist(predict(logistic))
max(predict(logistic))
min(predict(logistic))
```
```{r}
# 4. Ridge regression

```
```{r}
# 5. Lasso regression
# 
```
```{r}
# 6. Tree
plot(tree(Class ~ ., data = raisins))
text(tree(Class ~ ., data = raisins))
```




